const conf = {
    "Alia": {
        b64: false,
        imgs: [,
            'alia/alia00_background_3x.jpg',
            'alia/alia00_eruption_3x.jpg',
            'alia/alia00_Filaments_3x.jpg',
            'alia/alia00_Meduse_3x.jpg',
            'alia/alia00_purpleMoon_3x.jpg',
            'alia/alia00_redTexture_3x.jpg',
            'alia/alia00_Sapin_3x.jpg',
            'alia/alia00_Sapin01_3x.jpg',
            'alia/alia00_Sapin02_3x.jpg',
            'alia/alia00_Sperme_3x.jpg',
            'alia/alia00_turquoiseSea_3x.jpg',
        ],
        backgroundImg: 'backgrounds/myPaint.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },

    "Alia99": {
        b64: false,
        imgs: [,
            'Alia/Alia99.jpg', 'Alia/Alia99_Sapin02_3x.jpg',
        ],
        backgroundImg: 'myPaint.jpg',
        snowBallImg: 'GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },

    //------------------------------------------------------------- ,
    "Gigaro": {
        b64: false,
        imgs: [,
            'NousDeux2x.jpg',
            'Juin.jpg',
            'gigaro/Elisabeth_200_0_0_2x.jpg',
            'gigaro/Elisabeth_200_0_0_3x.jpg',
        ],
        backgroundImg: 'gigaro/GigaroDrone.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_3x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "MereNoel": {
        b64: false,
        imgs: [,
            //'MereNoel.jpg',
            'mereNoel/MereNoelCamille.jpg',
            'mereNoel/MereNoelCamille_0_0_200_2x.jpg',
            'mereNoel/MereNoelCamille_0_0_200_3x.jpg',
            'mereNoel/MereNoelCamille_200_200_200_2x.jpg',
            'MereNoelCamille_200_200_200_3x.jpg',
            //'MereNoelIsa.jpg',
            //'MereNoelIsa_200_0_0_2x.jpg',
            'mereNoel/MereNoelIsa_200_0_0_3x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_2x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_3x.jpg',
            'mereNoel/MereNoel_200_0_0_2x.jpg',
            'mereNoel/MereNoel_200_0_0_3x.jpg',
            'mereNoel/MereNoel_200_200_0_2x.jpg',
            'mereNoel/MereNoel_200_200_0_3x.jpg',
            'mereNoel/MereNoel_200_200_200_2x.jpg',
            'mereNoel/MereNoel_200_200_200_3x.jpg',
        ],
        backgroundImg: 'background/background.jpg',
        snowBallImg: 'mereNoel/MereNoel_200_0_0_2x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 8,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "IsaFamily": {
        imgs: [,
            'isaFamily/Camille2x.jpg',
            'isaFamily/Fabio2x2x.jpg',
            'isaFamily/Mael.jpg',
            'isaFamily/MaelPereNoel2x.jpg',
            'NousDeux2x.jpg',
            'NousDeux2x2x.jpg',
            'NousDeux022x.jpg',
            'Pepette2x.jpg',
            'PereNoel.jpg',
            //'alia00.jpg',
        ],

        backgroundImg: 'background/background.jpg',
        snowBallImg: 'background/maison.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 6,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Joevin": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/JoMaSki_JoMaison_3x.jpg',
        backgroundImg: 'lojo/JoMaison01.jpg',
        // snowBallImg : 'myPaint.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Loriane": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/LoSecours_Sapin01_3x.jpg',
        backgroundImg: 'background.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Udps41": {
        b64: false,
        imgs: [],
        snowBallImg: 'udps41/Udps41Jaune_redTexture_3x.jpg',
        backgroundImg: 'udps41/Udps41.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Test": {
        b64: false,
        imgs: ['alia/Xalia99.jpg'],
        // backgroundImg : 'background.jpg',
        backgroundImg: 'backgrounds/filaments.jpg',
        snowBallImg: 'isaFamily/maison.jpg',

        bowlsCount: 1,
        bowlsPerOrbit: 3,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
}
export default conf
