const conf = {
    "Alia": {
        b64: false,
        imgs: [,
            'alia/alia00_background_3x.jpg',
            'alia/alia00_eruption_3x.jpg',
            'alia/alia00_Filaments_3x.jpg',
            'alia/alia00_Meduse_3x.jpg',
            'alia/alia00_purpleMoon_3x.jpg',
            'alia/alia00_redTexture_3x.jpg',
            'alia/alia00_Sapin_3x.jpg',
            'alia/alia00_Sapin01_3x.jpg',
            'alia/alia00_Sapin02_3x.jpg',
            'alia/alia00_Sperme_3x.jpg',
            'alia/alia00_turquoiseSea_3x.jpg',
        ],
        backgroundImg: 'backgrounds/myPaint.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },

    "Alia99": {
        b64: false,
        imgs: [,
            'Alia/Alia99.jpg', 'Alia/Alia99_Sapin02_3x.jpg',
        ],
        backgroundImg: 'myPaint.jpg',
        snowBallImg: 'GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },
    "bb": {
        b64: false,
        imgs: [
    'bb/BebeCochon_Filaments_3x.jpg',
'bb/BebeCochon_Meduse_3x.jpg',
'bb/BebeCochon_Sapin01_3x.jpg',
'bb/BebeCochon_Sapin02_3x.jpg',
'bb/BebeCochon_Sapin02_Filaments_3x_3x.jpg',
'bb/BebeCochon_Sapin_3x.jpg',
'bb/BebeCochon_background2x_3x.jpg',
'bb/BebeCochon_background_3x.jpg',
'bb/BebeCochon_eruption_3x.jpg',
'bb/BebeCochon_myPaint_3x.jpg',
'bb/BebeCochon_purpleMoon_3x.jpg',
'bb/BebeCochon_redTexture_3x.jpg',
'bb/BebeCochon_turquoiseSea_3x.jpg',
'bb/Dino_Filaments_3x.jpg',
'bb/Dino_Meduse_3x.jpg',
'bb/Dino_Sapin01_3x.jpg',
'bb/Dino_Sapin02_3x.jpg',
'bb/Dino_Sapin02_Filaments_3x_3x.jpg',
'bb/Dino_Sapin_3x.jpg',
'bb/Dino_background2x_3x.jpg',
'bb/Dino_background_3x.jpg',
'bb/Dino_eruption_3x.jpg',
'bb/Dino_myPaint_3x.jpg',
'bb/Dino_purpleMoon_3x.jpg',
'bb/Dino_redTexture_3x.jpg',
'bb/Dino_turquoiseSea_3x.jpg',
'bb/Grenouille_Filaments_3x.jpg',
'bb/Grenouille_Meduse_3x.jpg',
'bb/Grenouille_Sapin01_3x.jpg',
'bb/Grenouille_Sapin02_3x.jpg',
'bb/Grenouille_Sapin02_Filaments_3x_3x.jpg',
'bb/Grenouille_Sapin_3x.jpg',
'bb/Grenouille_background2x_3x.jpg',
'bb/Grenouille_background_3x.jpg',
'bb/Grenouille_eruption_3x.jpg',
'bb/Grenouille_myPaint_3x.jpg',
'bb/Grenouille_purpleMoon_3x.jpg',
'bb/Grenouille_redTexture_3x.jpg',
'bb/Grenouille_turquoiseSea_3x.jpg',
'bb/Hochet_Filaments_3x.jpg',
'bb/Hochet_Meduse_3x.jpg',
'bb/Hochet_Sapin01_3x.jpg',
'bb/Hochet_Sapin02_3x.jpg',
'bb/Hochet_Sapin02_Filaments_3x_3x.jpg',
'bb/Hochet_Sapin_3x.jpg',
'bb/Hochet_background2x_3x.jpg',
'bb/Hochet_background_3x.jpg',
'bb/Hochet_eruption_3x.jpg',
'bb/Hochet_myPaint_3x.jpg',
'bb/Hochet_purpleMoon_3x.jpg',
'bb/Hochet_redTexture_3x.jpg',
'bb/Hochet_turquoiseSea_3x.jpg',
'bb/Kawai_Filaments_3x.jpg',
'bb/Kawai_Meduse_3x.jpg',
'bb/Kawai_Sapin01_3x.jpg',
'bb/Kawai_Sapin02_3x.jpg',
'bb/Kawai_Sapin02_Filaments_3x_3x.jpg',
'bb/Kawai_Sapin_3x.jpg',
'bb/Kawai_background2x_3x.jpg',
'bb/Kawai_background_3x.jpg',
'bb/Kawai_eruption_3x.jpg',
'bb/Kawai_myPaint_3x.jpg',
'bb/Kawai_purpleMoon_3x.jpg',
'bb/Kawai_redTexture_3x.jpg',
'bb/Kawai_turquoiseSea_3x.jpg',
'bb/LeLoup_Filaments_3x.jpg',
'bb/LeLoup_Meduse_3x.jpg',
'bb/LeLoup_Sapin01_3x.jpg',
'bb/LeLoup_Sapin02_3x.jpg',
'bb/LeLoup_Sapin02_Filaments_3x_3x.jpg',
'bb/LeLoup_Sapin_3x.jpg',
'bb/LeLoup_background2x_3x.jpg',
'bb/LeLoup_background_3x.jpg',
'bb/LeLoup_eruption_3x.jpg',
'bb/LeLoup_myPaint_3x.jpg',
'bb/LeLoup_purpleMoon_3x.jpg',
'bb/LeLoup_redTexture_3x.jpg',
'bb/LeLoup_turquoiseSea_3x.jpg',
'bb/OurangOutang2_Filaments_3x.jpg',
'bb/OurangOutang2_Meduse_3x.jpg',
'bb/OurangOutang2_Sapin01_3x.jpg',
'bb/OurangOutang2_Sapin02_3x.jpg',
'bb/OurangOutang2_Sapin02_Filaments_3x_3x.jpg',
'bb/OurangOutang2_Sapin_3x.jpg',
'bb/OurangOutang2_background2x_3x.jpg',
'bb/OurangOutang2_background_3x.jpg',
'bb/OurangOutang2_eruption_3x.jpg',
'bb/OurangOutang2_myPaint_3x.jpg',
'bb/OurangOutang2_purpleMoon_3x.jpg',
'bb/OurangOutang2_redTexture_3x.jpg',
'bb/OurangOutang2_turquoiseSea_3x.jpg',
'bb/OurangOutang_Filaments_3x.jpg',
'bb/OurangOutang_Meduse_3x.jpg',
'bb/OurangOutang_Sapin01_3x.jpg',
'bb/OurangOutang_Sapin02_3x.jpg',
'bb/OurangOutang_Sapin02_Filaments_3x_3x.jpg',
'bb/OurangOutang_Sapin_3x.jpg',
'bb/OurangOutang_background2x_3x.jpg',
'bb/OurangOutang_background_3x.jpg',
'bb/OurangOutang_eruption_3x.jpg',
'bb/OurangOutang_myPaint_3x.jpg',
'bb/OurangOutang_purpleMoon_3x.jpg',
'bb/OurangOutang_redTexture_3x.jpg',
'bb/OurangOutang_turquoiseSea_3x.jpg',
'bb/PouponGore_Filaments_3x.jpg',
'bb/PouponGore_Meduse_3x.jpg',
'bb/PouponGore_Sapin01_3x.jpg',
'bb/PouponGore_Sapin02_3x.jpg',
'bb/PouponGore_Sapin02_Filaments_3x_3x.jpg',
'bb/PouponGore_Sapin_3x.jpg',
'bb/PouponGore_background2x_3x.jpg',
'bb/PouponGore_background_3x.jpg',
'bb/PouponGore_eruption_3x.jpg',
'bb/PouponGore_myPaint_3x.jpg',
'bb/PouponGore_purpleMoon_3x.jpg',
'bb/PouponGore_redTexture_3x.jpg',
'bb/PouponGore_turquoiseSea_3x.jpg',
'bb/Sanglier_Filaments_3x.jpg',
'bb/Sanglier_Meduse_3x.jpg',
'bb/Sanglier_Sapin01_3x.jpg',
'bb/Sanglier_Sapin02_3x.jpg',
'bb/Sanglier_Sapin02_Filaments_3x_3x.jpg',
'bb/Sanglier_Sapin_3x.jpg',
'bb/Sanglier_background2x_3x.jpg',
'bb/Sanglier_background_3x.jpg',
'bb/Sanglier_eruption_3x.jpg',
'bb/Sanglier_myPaint_3x.jpg',
'bb/Sanglier_purpleMoon_3x.jpg',
'bb/Sanglier_redTexture_3x.jpg',
'bb/Sanglier_turquoiseSea_3x.jpg',
'bb/lapinou_Filaments_3x.jpg',
'bb/lapinou_Meduse_3x.jpg',
'bb/lapinou_Sapin01_3x.jpg',
'bb/lapinou_Sapin02_3x.jpg',
'bb/lapinou_Sapin02_Filaments_3x_3x.jpg',
'bb/lapinou_Sapin_3x.jpg',
'bb/lapinou_background2x_3x.jpg',
'bb/lapinou_background_3x.jpg',
'bb/lapinou_eruption_3x.jpg',
'bb/lapinou_myPaint_3x.jpg',
'bb/lapinou_purpleMoon_3x.jpg',
'bb/lapinou_redTexture_3x.jpg',
'bb/lapinou_turquoiseSea_3x.jpg',
'bb/ours01_Filaments_3x.jpg',
'bb/ours01_Meduse_3x.jpg',
'bb/ours01_Sapin01_3x.jpg',
'bb/ours01_Sapin02_3x.jpg',
'bb/ours01_Sapin02_Filaments_3x_3x.jpg',
'bb/ours01_Sapin_3x.jpg',
'bb/ours01_background2x_3x.jpg',
'bb/ours01_background_3x.jpg',
'bb/ours01_eruption_3x.jpg',
'bb/ours01_myPaint_3x.jpg',
'bb/ours01_purpleMoon_3x.jpg',
'bb/ours01_redTexture_3x.jpg',
'bb/ours01_turquoiseSea_3x.jpg',
        ],
        backgroundImg: 'backgrounds/ciel.jpg',
        snowBallImg: 'backgrounds/cielRoseBleu.jpg',
        bowlsCount: 20,
        bowlsPerOrbit: 10,
        snowGlobeRadius: 15,
        thingMeshRadius: 3,
        flakesCount: 0,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },


    //------------------------------------------------------------- ,
    "Gigaro": {
        b64: false,
        imgs: [,
            'NousDeux2x.jpg',
            'Juin.jpg',
            'gigaro/Elisabeth_200_0_0_2x.jpg',
            'gigaro/Elisabeth_200_0_0_3x.jpg',
        ],
        backgroundImg: 'gigaro/GigaroDrone.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_3x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "MereNoel": {
        b64: false,
        imgs: [,
            //'MereNoel.jpg',
            'mereNoel/MereNoelCamille.jpg',
            'mereNoel/MereNoelCamille_0_0_200_2x.jpg',
            'mereNoel/MereNoelCamille_0_0_200_3x.jpg',
            'mereNoel/MereNoelCamille_200_200_200_2x.jpg',
            'MereNoelCamille_200_200_200_3x.jpg',
            //'MereNoelIsa.jpg',
            //'MereNoelIsa_200_0_0_2x.jpg',
            'mereNoel/MereNoelIsa_200_0_0_3x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_2x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_3x.jpg',
            'mereNoel/MereNoel_200_0_0_2x.jpg',
            'mereNoel/MereNoel_200_0_0_3x.jpg',
            'mereNoel/MereNoel_200_200_0_2x.jpg',
            'mereNoel/MereNoel_200_200_0_3x.jpg',
            'mereNoel/MereNoel_200_200_200_2x.jpg',
            'mereNoel/MereNoel_200_200_200_3x.jpg',
        ],
        backgroundImg: 'background/background.jpg',
        snowBallImg: 'mereNoel/MereNoel_200_0_0_2x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 8,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "IsaFamily": {
        imgs: [,
            'isaFamily/Camille2x.jpg',
            'isaFamily/Fabio2x2x.jpg',
            'isaFamily/Mael.jpg',
            'isaFamily/MaelPereNoel2x.jpg',
            'NousDeux2x.jpg',
            'NousDeux2x2x.jpg',
            'NousDeux022x.jpg',
            'Pepette2x.jpg',
            'PereNoel.jpg',
            //'alia00.jpg',
        ],

        backgroundImg: 'background/background.jpg',
        snowBallImg: 'background/maison.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 6,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Joevin": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/JoMaSki_JoMaison_3x.jpg',
        backgroundImg: 'lojo/JoMaison01.jpg',
        // snowBallImg : 'myPaint.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Loriane": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/LoSecours_Sapin01_3x.jpg',
        backgroundImg: 'background.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "LoJoMa": {
        b64: false,
        imgs: [

'lojo/LoJoSki_Filaments_3x.jpg',
'lojo/LoMaManege_Meduse_3x.jpg',
'lojo/LoJoMaFiance_Sapin01_3x.jpg',
'lojo/LoMaBoucherie_redTexture_3x.jpg',
'lojo/LoJoMaHalloween_eruption_3x.jpg',
'lojo/LoMaHalloween_redTexture_3x.jpg',
'lojo/LoJoMaHalloween_myPaint_3x.jpg',
'lojo/LoMaMartroi_eruption_3x.jpg',
'lojo/LoJoMaGaufre_Sapin01_3x.jpg',
'lojo/JoMaison_Sapin01_3x.jpg',
'lojo/LoJoMaVoiture_purpleMoon_3x.jpg',
'lojo/JoMaison_Meduse_3x.jpg',
'lojo/LoMaMartroi_redTexture_3x.jpg',
'lojo/JoMaison01_Sapin_3x.jpg',
'lojo/LoJoHalloween_purpleMoon_3x.jpg',
'lojo/LoJoMaHalloween_turquoiseSea_3x.jpg',
'lojo/LoMer_Meduse_3x.jpg',
'lojo/LoMaBalneo_Sapin_3x.jpg',
'lojo/LoJoMaAnniv_myPaint_3x.jpg',
'lojo/LoMaManege_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoJoHalloween_background_3x.jpg',
'lojo/LoSecours_Sapin_3x.jpg',
'lojo/LoJoMaGaufre_myPaint_3x.jpg',
'lojo/JoGato_Sapin02_3x.jpg',
'lojo/LoJoSki_turquoiseSea_3x.jpg',
'lojo/LoSecours_Sapin01_3x.jpg',
'lojo/LoJoMaAe_background_3x.jpg',
'lojo/LoMer_eruption_3x.jpg',
'lojo/LoMaBalneo_turquoiseSea_3x.jpg',
'lojo/LoJoMaGaufre_eruption_3x.jpg',
'lojo/LoJoMaGaufre_background2x_3x.jpg',
'lojo/LoJoSki_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoJoMaAe_Sapin_3x.jpg',
'lojo/LoJoMaAe_Sapin02_Filaments_3x_3x.jpg',
'lojo/JoMaison01_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoMaHalloween_redTexture_3x.jpg',
'lojo/LoRose_myPaint_3x.jpg',
'lojo/LoMaHalloween_background2x_3x.jpg',
'lojo/LoJoMaFiance_background_3x.jpg',
'lojo/LoJoMaAnniv_eruption_3x.jpg',
'lojo/JoMaSki_Sapin02_3x.jpg',
'lojo/JoMaison01_background2x_3x.jpg',
'lojo/LoMaBoucherie_myPaint_3x.jpg',
'lojo/LoJoMaSKi01_redTexture_3x.jpg',
'lojo/LoMer_Sapin01_3x.jpg',
'lojo/LoJoMaSki02_Meduse_3x.jpg',
'lojo/LoJoMaAe_myPaint_3x.jpg',


        ],
        snowBallImg: 'lojo/LoJoMaGaufre_myPaint_3x.jpg',
        backgroundImg: 'backgrounds/background.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 7,
        bowlsPerOrbit: 7,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },


    //------------------------------------------------------------- ,
    "Udps41": {
        b64: false,
        imgs: [],
        snowBallImg: 'udps41/Udps41Jaune_redTexture_3x.jpg',
        backgroundImg: 'udps41/Udps41.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Test": {
        b64: false,
        imgs: ['alia/Xalia99.jpg'],
        // backgroundImg : 'background.jpg',
        backgroundImg: 'backgrounds/filaments.jpg',
        snowBallImg: 'isaFamily/maison.jpg',

        bowlsCount: 1,
        bowlsPerOrbit: 3,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
}
export default conf
