const conf = {
    "Alia": {
        b64: false,
        imgs: [,
            'alia/alia00_background_3x.jpg',
            'alia/alia00_eruption_3x.jpg',
            'alia/alia00_Filaments_3x.jpg',
            'alia/alia00_Meduse_3x.jpg',
            'alia/alia00_purpleMoon_3x.jpg',
            'alia/alia00_redTexture_3x.jpg',
            'alia/alia00_Sapin_3x.jpg',
            'alia/alia00_Sapin01_3x.jpg',
            'alia/alia00_Sapin02_3x.jpg',
            'alia/alia00_Sperme_3x.jpg',
            'alia/alia00_turquoiseSea_3x.jpg',
        ],
        backgroundImg: 'backgrounds/myPaint.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },

    "Alia99": {
        b64: false,
        imgs: [,
            'Alia/Alia99.jpg', 'Alia/Alia99_Sapin02_3x.jpg',
        ],
        backgroundImg: 'myPaint.jpg',
        snowBallImg: 'GigaroDrone_128_128_128_2x.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 500,
    },
    "bb": {
        b64: false,
        imgs: [
//'bb/OurangOutang_CielRoseBleu_1_2x.jpg',
//'bb/OurangOutang_CielRoseBleu_1_3x.jpg',
//'bb/OurangOutang_CielRoseBleu_1_4x.jpg',
//'bb/Ourson_black_1_2x.jpg',
//'bb/Ourson_Filaments_1_3x.jpg',
//'bb/Oursons.jpg',
//'bb/Oursons_eruption_1_2x.jpg',
'bb/Ourson_$_50_50_50_x_2_3x.jpg',
'bb/Ourson_$_50_50_50_x_2_4x.jpg',
////'bb/x1080_Meduse_1_2x.jpg',
//'bb/x1080.jpg',
'bb/LeLoup_eruption_2_4x.jpg',
        ],
        backgroundImg: 'backgrounds/Univers.jpg',
        snowBallImg: 'bb/LeLoup_eruption_2_4x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 5000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Binky": {
        b64: false,
        imgs: [,
            'NousDeux2x.jpg',
            'Juin.jpg',
            'gigaro/Elisabeth_200_0_0_2x.jpg',
            'gigaro/Elisabeth_200_0_0_3x.jpg',
        ],
        backgroundImg: '',
        snowBallImg: 'Binky_y.jpg',
        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },


    //------------------------------------------------------------- ,
    "Gigaro": {
        b64: false,
        imgs: [,
            'NousDeux2x.jpg',
            'Juin.jpg',
            'gigaro/Elisabeth_200_0_0_2x.jpg',
            'gigaro/Elisabeth_200_0_0_3x.jpg',
        ],
        backgroundImg: 'gigaro/GigaroDrone.jpg',
        snowBallImg: 'gigaro/GigaroDrone_128_128_128_3x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Hugues": {
        b64: false,
        imgs: [
'hugues/Cathy02_cielRoseBleu_1_3x.jpg',
'hugues/Cathy02_ciel_1_3x.jpg',
'hugues/Cathy02_eruption_1_3x.jpg',
'hugues/Cathy02_purpleMoon_1_3x.jpg',
'hugues/Cathy02_redTexture_1_3x.jpg',
'hugues/Cathy02_turquoiseSea_1_3x.jpg',
'hugues/CathyChien_Filaments_1_3x.jpg',
'hugues/CathyChien_Meduse_1_3x.jpg',
'hugues/CathyChien_Sapin01_1_3x.jpg',
'hugues/CathyChien_Sapin02_1_3x.jpg',
'hugues/CathyChien_Sapin_1_3x.jpg',
'hugues/CathyChien_cielRoseBleu_1_3x.jpg',
'hugues/CathyChien_ciel_1_3x.jpg',
'hugues/CathyChien_eruption_1_3x.jpg',
'hugues/CathyChien_purpleMoon_1_3x.jpg',
'hugues/CathyChien_redTexture_1_3x.jpg',
'hugues/CathyChien_turquoiseSea_1_3x.jpg',
'hugues/HuguesCafe_Filaments_1_3x.jpg',
'hugues/HuguesCafe_Meduse_1_3x.jpg',
'hugues/HuguesCafe_Sapin01_1_3x.jpg',
'hugues/HuguesCafe_Sapin02_1_3x.jpg',
'hugues/HuguesCafe_Sapin_1_3x.jpg',
'hugues/HuguesCafe_cielRoseBleu_1_3x.jpg',
'hugues/HuguesCafe_ciel_1_3x.jpg',
'hugues/HuguesCafe_eruption_1_3x.jpg',
'hugues/HuguesCafe_purpleMoon_1_3x.jpg',
'hugues/HuguesCafe_redTexture_1_3x.jpg',
'hugues/HuguesCafe_turquoiseSea_1_3x.jpg',
'hugues/HuguesCarte_Filaments_1_3x.jpg',
'hugues/HuguesCarte_Meduse_1_3x.jpg',
'hugues/HuguesCarte_Sapin01_1_3x.jpg',
'hugues/HuguesCarte_Sapin02_1_3x.jpg',
'hugues/HuguesCarte_Sapin_1_3x.jpg',
'hugues/HuguesCarte_cielRoseBleu_1_3x.jpg',
'hugues/HuguesCarte_eruption_1_3x.jpg',
'hugues/HuguesCarte_purpleMoon_1_3x.jpg',
'hugues/HuguesCarte_redTexture_1_3x.jpg',
'hugues/HuguesCarte_turquoiseSea_1_3x.jpg',
'hugues/HuguesCathy02_Filaments_1_3x.jpg',
'hugues/HuguesCathy02_Meduse_1_3x.jpg',
'hugues/HuguesCathy02_Sapin01_1_3x.jpg',
'hugues/HuguesCathy02_Sapin02_1_3x.jpg',
'hugues/HuguesCathy02_Sapin_1_3x.jpg',
'hugues/HuguesCathy02_cielRoseBleu_1_3x.jpg',
'hugues/HuguesCathy02_eruption_1_3x.jpg',
'hugues/HuguesCathy02_purpleMoon_1_3x.jpg',
'hugues/HuguesCathy02_redTexture_1_3x.jpg',
'hugues/HuguesCathy02_turquoiseSea_1_3x.jpg',
'hugues/HuguesCathy03_Filaments_1_3x.jpg',
'hugues/HuguesCathy03_Meduse_1_3x.jpg',
'hugues/HuguesCathy03_Sapin01_1_3x.jpg',
'hugues/HuguesCathy03_Sapin02_1_3x.jpg',
'hugues/HuguesCathy03_Sapin_1_3x.jpg',
'hugues/HuguesCathy03_cielRoseBleu_1_3x.jpg',
'hugues/HuguesCathy03_eruption_1_3x.jpg',
'hugues/HuguesCathy03_purpleMoon_1_3x.jpg',
'hugues/HuguesCathy03_redTexture_1_3x.jpg',
'hugues/HuguesCathy03_turquoiseSea_1_3x.jpg',
'hugues/HuguesCathy_Filaments_1_3x.jpg',
'hugues/HuguesCathy_Meduse_1_3x.jpg',
'hugues/HuguesCathy_Sapin01_1_3x.jpg',
'hugues/HuguesCathy_Sapin02_1_3x.jpg',
'hugues/HuguesCathy_Sapin_1_3x.jpg',
'hugues/HuguesCathy_cielRoseBleu_1_3x.jpg',
'hugues/HuguesCathy_eruption_1_3x.jpg',
'hugues/HuguesCathy_purpleMoon_1_3x.jpg',
'hugues/HuguesCathy_redTexture_1_3x.jpg',
'hugues/HuguesCathy_turquoiseSea_1_3x.jpg',
'hugues/HuguesNola_cielRoseBleu_1_3x.jpg',
'hugues/HuguesNola_ciel_1_3x.jpg',
        ],
       backgroundImg: 'backgrounds/Univers.jpg',
        snowBallImg: 'backgrounds/Asses2026.jpg',

        bowlsCount: 8,
        bowlsPerOrbit: 5,
        snowGlobeRadius: 95,
        thingMeshRadius: 15,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 350,
    },


    //------------------------------------------------------------- ,
    "MereNoel": {
        b64: false,
        imgs: [,
            //'MereNoel.jpg',
            'mereNoel/MereNoelCamille.jpg',
            'mereNoel/MereNoelCamille_0_0_200_2x.jpg',
            'mereNoel/MereNoelCamille_0_0_200_3x.jpg',
            'mereNoel/MereNoelCamille_200_200_200_2x.jpg',
            'MereNoelCamille_200_200_200_3x.jpg',
            //'MereNoelIsa.jpg',
            //'MereNoelIsa_200_0_0_2x.jpg',
            'mereNoel/MereNoelIsa_200_0_0_3x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_2x.jpg',
            'mereNoel/MereNoelIsa_200_200_200_3x.jpg',
            'mereNoel/MereNoel_200_0_0_2x.jpg',
            'mereNoel/MereNoel_200_0_0_3x.jpg',
            'mereNoel/MereNoel_200_200_0_2x.jpg',
            'mereNoel/MereNoel_200_200_0_3x.jpg',
            'mereNoel/MereNoel_200_200_200_2x.jpg',
            'mereNoel/MereNoel_200_200_200_3x.jpg',
        ],
        backgroundImg: 'background/background.jpg',
        snowBallImg: 'mereNoel/MereNoel_200_0_0_2x.jpg',
        bowlsCount: 5,
        bowlsPerOrbit: 8,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "IsaFamily": {
        imgs: [,
            'isaFamily/Camille2x.jpg',
            'isaFamily/Fabio2x2x.jpg',
            'isaFamily/Mael.jpg',
            'isaFamily/MaelPereNoel2x.jpg',
            'NousDeux2x.jpg',
            'NousDeux2x2x.jpg',
            'NousDeux022x.jpg',
            'Pepette2x.jpg',
            'PereNoel.jpg',
            //'alia00.jpg',
        ],

        backgroundImg: 'background/background.jpg',
        snowBallImg: 'background/maison.jpg',
        bowlsCount: 10,
        bowlsPerOrbit: 6,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "Joevin": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/JoMaSki_JoMaison_3x.jpg',
        backgroundImg: 'lojo/JoMaison01.jpg',
        // snowBallImg : 'myPaint.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Loriane": {
        b64: false,
        imgs: [],
        snowBallImg: 'lojo/LoSecours_Sapin01_3x.jpg',
        backgroundImg: 'background.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 150,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },

    //------------------------------------------------------------- ,
    "LoJoMa": {
        b64: false,
        imgs: [

'lojo/LoJoSki_Filaments_3x.jpg',
'lojo/LoMaManege_Meduse_3x.jpg',
'lojo/LoJoMaFiance_Sapin01_3x.jpg',
'lojo/LoMaBoucherie_redTexture_3x.jpg',
'lojo/LoJoMaHalloween_eruption_3x.jpg',
'lojo/LoMaHalloween_redTexture_3x.jpg',
'lojo/LoJoMaHalloween_myPaint_3x.jpg',
'lojo/LoMaMartroi_eruption_3x.jpg',
'lojo/LoJoMaGaufre_Sapin01_3x.jpg',
'lojo/JoMaison_Sapin01_3x.jpg',
'lojo/LoJoMaVoiture_purpleMoon_3x.jpg',
'lojo/JoMaison_Meduse_3x.jpg',
'lojo/LoMaMartroi_redTexture_3x.jpg',
'lojo/JoMaison01_Sapin_3x.jpg',
'lojo/LoJoHalloween_purpleMoon_3x.jpg',
'lojo/LoJoMaHalloween_turquoiseSea_3x.jpg',
'lojo/LoMer_Meduse_3x.jpg',
'lojo/LoMaBalneo_Sapin_3x.jpg',
'lojo/LoJoMaAnniv_myPaint_3x.jpg',
'lojo/LoMaManege_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoJoHalloween_background_3x.jpg',
'lojo/LoSecours_Sapin_3x.jpg',
'lojo/LoJoMaGaufre_myPaint_3x.jpg',
'lojo/JoGato_Sapin02_3x.jpg',
'lojo/LoJoSki_turquoiseSea_3x.jpg',
'lojo/LoSecours_Sapin01_3x.jpg',
'lojo/LoJoMaAe_background_3x.jpg',
'lojo/LoMer_eruption_3x.jpg',
'lojo/LoMaBalneo_turquoiseSea_3x.jpg',
'lojo/LoJoMaGaufre_eruption_3x.jpg',
'lojo/LoJoMaGaufre_background2x_3x.jpg',
'lojo/LoJoSki_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoJoMaAe_Sapin_3x.jpg',
'lojo/LoJoMaAe_Sapin02_Filaments_3x_3x.jpg',
'lojo/JoMaison01_Sapin02_Filaments_3x_3x.jpg',
'lojo/LoMaHalloween_redTexture_3x.jpg',
'lojo/LoRose_myPaint_3x.jpg',
'lojo/LoMaHalloween_background2x_3x.jpg',
'lojo/LoJoMaFiance_background_3x.jpg',
'lojo/LoJoMaAnniv_eruption_3x.jpg',
'lojo/JoMaSki_Sapin02_3x.jpg',
'lojo/JoMaison01_background2x_3x.jpg',
'lojo/LoMaBoucherie_myPaint_3x.jpg',
'lojo/LoJoMaSKi01_redTexture_3x.jpg',
'lojo/LoMer_Sapin01_3x.jpg',
'lojo/LoJoMaSki02_Meduse_3x.jpg',
'lojo/LoJoMaAe_myPaint_3x.jpg',


        ],
        snowBallImg: 'lojo/LoJoMaGaufre_myPaint_3x.jpg',
        backgroundImg: 'backgrounds/background.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 7,
        bowlsPerOrbit: 7,
        snowGlobeRadius: 100,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },


    //------------------------------------------------------------- ,
    "Udps41": {
        b64: false,
        imgs: [],
        snowBallImg: 'udps41/Udps41Jaune_redTexture_3x.jpg',
        backgroundImg: 'udps41/Udps41.jpg',
        // snowBallImg : 'maison.jpg',

        bowlsCount: 0,
        bowlsPerOrbit: 0,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 1000,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
    //------------------------------------------------------------- ,
    "Test": {
        b64: false,
        imgs: ['alia/Xalia99.jpg'],
        // backgroundImg : 'background.jpg',
        backgroundImg: 'backgrounds/filaments.jpg',
        snowBallImg: 'isaFamily/maison.jpg',

        bowlsCount: 1,
        bowlsPerOrbit: 3,
        snowGlobeRadius: 75,
        thingMeshRadius: 20,
        flakesCount: 500,

        cameraFov: 60,
        cameraNear: 10,
        cameraFar: 10000,
        cameraX: 0,
        cameraY: 0,
        cameraZ: 400,
    },
}
export default conf
